import type { Metadata } from "next"
import Header from "@/components/layout/header"
import Footer from "@/components/layout/footer"

export const metadata: Metadata = {
  title: "Privacy Policy | CountryRoof",
  description: "CountryRoof privacy policy - how we collect, use, and protect your personal information.",
}

export default function PrivacyPolicyPage() {
  return (
    <>
      <Header />
      <main className="min-h-screen px-4 py-12 bg-background">
        <div className="max-w-4xl mx-auto space-y-8">
          <div className="space-y-2">
            <h1 className="text-4xl font-bold text-foreground">Privacy Policy</h1>
            <p className="text-muted-foreground text-sm">Last updated: April 04, 2025</p>
          </div>

          <div className="prose prose-sm max-w-none text-foreground space-y-6">
            {/* Introduction */}
            <section className="space-y-3">
              <p className="text-muted-foreground">
                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your
                information when You use the Service and tells You about Your privacy rights and how the law protects
                You.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">Interpretation and Definitions</h2>

              <div className="space-y-3">
                <h3 className="text-lg font-semibold text-foreground">Interpretation</h3>
                <p className="text-muted-foreground">
                  The words of which the initial letter is capitalized have meanings defined under the following
                  conditions. The following definitions shall have the same meaning regardless of whether they appear in
                  singular or in plural.
                </p>
              </div>

              <div className="space-y-3">
                <h3 className="text-lg font-semibold text-foreground">Definitions</h3>
                <p className="text-muted-foreground">For the purposes of this Privacy Policy:</p>
                <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                  <li>
                    <strong>Account</strong> means a unique account created for You to access our Service or parts of
                    our Service.
                  </li>
                  <li>
                    <strong>Affiliate</strong> means an entity that controls, is controlled by or is under common
                    control with a party, where "control" means ownership of 50% or more of the shares, equity interest
                    or other securities entitled to vote for election of directors or other managing authority.
                  </li>
                  <li>
                    <strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this
                    Agreement) refers to Countryroof Infratech, IRIS Tech Park, Unit No. 407.
                  </li>
                  <li>
                    <strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any
                    other device by a website, containing the details of Your browsing history on that website among its
                    many uses.
                  </li>
                  <li>
                    <strong>Country</strong> refers to: Haryana, India
                  </li>
                  <li>
                    <strong>Device</strong> means any device that can access the Service such as a computer, a cellphone
                    or a digital tablet.
                  </li>
                  <li>
                    <strong>Personal Data</strong> is any information that relates to an identified or identifiable
                    individual.
                  </li>
                  <li>
                    <strong>Service</strong> refers to the Website.
                  </li>
                  <li>
                    <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf
                    of the Company. It refers to third-party companies or individuals employed by the Company to
                    facilitate the Service, to provide the Service on behalf of the Company, to perform services related
                    to the Service or to assist the Company in analyzing how the Service is used.
                  </li>
                  <li>
                    <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of
                    the Service or from the Service infrastructure itself (for example, the duration of a page visit).
                  </li>
                  <li>
                    <strong>Website</strong> refers to Countryroof, accessible from countryroof.in
                  </li>
                  <li>
                    <strong>You</strong> means the individual accessing or using the Service, or the company, or other
                    legal entity on behalf of which such individual is accessing or using the Service, as applicable.
                  </li>
                </ul>
              </div>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">Collecting and Using Your Personal Data</h2>

              <div className="space-y-3">
                <h3 className="text-lg font-semibold text-foreground">Types of Data Collected</h3>

                <div className="space-y-3">
                  <h4 className="font-semibold text-foreground">Personal Data</h4>
                  <p className="text-muted-foreground">
                    While using Our Service, We may ask You to provide Us with certain personally identifiable
                    information that can be used to contact or identify You. Personally identifiable information may
                    include, but is not limited to:
                  </p>
                  <ul className="list-disc pl-6 space-y-1 text-muted-foreground">
                    <li>Email address</li>
                    <li>First name and last name</li>
                    <li>Phone number</li>
                    <li>Address, State, Province, ZIP/Postal code, City</li>
                    <li>Usage Data</li>
                  </ul>
                </div>

                <div className="space-y-3">
                  <h4 className="font-semibold text-foreground">Usage Data</h4>
                  <p className="text-muted-foreground">
                    Usage Data is collected automatically when using the Service. Usage Data may include information
                    such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version,
                    the pages of our Service that You visit, the time and date of Your visit, the time spent on those
                    pages, unique device identifiers and other diagnostic data.
                  </p>
                  <p className="text-muted-foreground">
                    When You access the Service by or through a mobile device, We may collect certain information
                    automatically, including, but not limited to, the type of mobile device You use, Your mobile device
                    unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile
                    Internet browser You use, unique device identifiers and other diagnostic data.
                  </p>
                </div>
              </div>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">Tracking Technologies and Cookies</h2>

              <p className="text-muted-foreground">
                We use Cookies and similar tracking technologies to track the activity on Our Service and store certain
                information. Tracking technologies used are beacons, tags, and scripts to collect and track information
                and to improve and analyze Our Service. The technologies We use may include:
              </p>

              <ul className="list-disc pl-6 space-y-3 text-muted-foreground">
                <li>
                  <strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can
                  instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if
                  You do not accept Cookies, You may not be able to use some parts of our Service.
                </li>
                <li>
                  <strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small
                  electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel
                  gifs) that permit the Company, for example, to count users who have visited those pages or opened an
                  email and for other related website statistics.
                </li>
              </ul>

              <p className="text-muted-foreground mt-4">
                Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or
                mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web
                browser.
              </p>

              <div className="space-y-3 mt-4">
                <h4 className="font-semibold text-foreground">
                  We use both Session and Persistent Cookies for the following purposes:
                </h4>
                <ul className="space-y-2">
                  <li className="text-muted-foreground">
                    <strong>Necessary / Essential Cookies (Session):</strong> These Cookies are essential to provide You
                    with services available through the Website and to enable You to use some of its features. They help
                    to authenticate users and prevent fraudulent use of user accounts.
                  </li>
                  <li className="text-muted-foreground">
                    <strong>Cookies Policy / Notice Acceptance Cookies (Persistent):</strong> These Cookies identify if
                    users have accepted the use of cookies on the Website.
                  </li>
                  <li className="text-muted-foreground">
                    <strong>Functionality Cookies (Persistent):</strong> These Cookies allow us to remember choices You
                    make when You use the Website, such as remembering your login details or language preference.
                  </li>
                </ul>
              </div>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">Use of Your Personal Data</h2>

              <p className="text-muted-foreground">The Company may use Personal Data for the following purposes:</p>

              <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
                <li>To manage Your Account and registration as a user of the Service.</li>
                <li>
                  For the performance of a contract: the development, compliance and undertaking of the purchase
                  contract for the products, items or services You have purchased.
                </li>
                <li>
                  To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication
                  regarding updates or informative communications.
                </li>
                <li>
                  To provide You with news, special offers and general information about other goods, services and
                  events which we offer.
                </li>
                <li>To manage Your requests to Us.</li>
                <li>For business transfers and evaluations of mergers or acquisitions.</li>
                <li>
                  For data analysis, identifying usage trends, and evaluating the effectiveness of promotional
                  campaigns.
                </li>
              </ul>

              <p className="text-muted-foreground mt-4">
                We may share Your personal information with Service Providers, for business transfers, with Affiliates,
                with business partners, with other users when You share information publicly, and with Your consent.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">Retention of Your Personal Data</h2>

              <p className="text-muted-foreground">
                The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in
                this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with
                our legal obligations and resolve disputes. Usage Data is generally retained for a shorter period of
                time, except when this data is used to strengthen the security or improve the functionality of Our
                Service.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">Transfer of Your Personal Data</h2>

              <p className="text-muted-foreground">
                Your information, including Personal Data, is processed at the Company's operating offices and in any
                other places where the parties involved in the processing are located. Your consent to this Privacy
                Policy followed by Your submission of such information represents Your agreement to that transfer. The
                Company will take all steps reasonably necessary to ensure that Your data is treated securely and in
                accordance with this Privacy Policy.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">Delete Your Personal Data</h2>

              <p className="text-muted-foreground">
                You have the right to delete or request that We assist in deleting the Personal Data that We have
                collected about You. You may update, amend, or delete Your information at any time by signing in to Your
                Account and visiting the account settings section. You may also contact Us to request access to,
                correct, or delete any personal information that You have provided to Us.
              </p>
              <p className="text-muted-foreground mt-2">
                Please note that We may need to retain certain information when we have a legal obligation or lawful
                basis to do so.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">Disclosure of Your Personal Data</h2>

              <div className="space-y-3">
                <h3 className="font-semibold text-foreground">Business Transactions</h3>
                <p className="text-muted-foreground">
                  If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be
                  transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a
                  different Privacy Policy.
                </p>
              </div>

              <div className="space-y-3">
                <h3 className="font-semibold text-foreground">Law Enforcement</h3>
                <p className="text-muted-foreground">
                  Under certain circumstances, the Company may be required to disclose Your Personal Data if required to
                  do so by law or in response to valid requests by public authorities (e.g. a court or a government
                  agency).
                </p>
              </div>

              <div className="space-y-3">
                <h3 className="font-semibold text-foreground">Other Legal Requirements</h3>
                <p className="text-muted-foreground">
                  The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
                </p>
                <ul className="list-disc pl-6 space-y-1 text-muted-foreground">
                  <li>Comply with a legal obligation</li>
                  <li>Protect and defend the rights or property of the Company</li>
                  <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                  <li>Protect the personal safety of Users of the Service or the public</li>
                  <li>Protect against legal liability</li>
                </ul>
              </div>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">Security of Your Personal Data</h2>

              <p className="text-muted-foreground">
                The security of Your Personal Data is important to Us, but remember that no method of transmission over
                the Internet, or method of electronic storage is 100% secure. While We strive to use commercially
                acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">Children's Privacy</h2>

              <p className="text-muted-foreground">
                Our Service does not address anyone under the age of 13. We do not knowingly collect personally
                identifiable information from anyone under the age of 13. If You are a parent or guardian and You are
                aware that Your child has provided Us with Personal Data, please contact Us. If We need to rely on
                consent as a legal basis for processing Your information and Your country requires consent from a
                parent, We may require Your parent's consent before We collect and use that information.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">Links to Other Websites</h2>

              <p className="text-muted-foreground">
                Our Service may contain links to other websites that are not operated by Us. If You click on a third
                party link, You will be directed to that third party's site. We strongly advise You to review the
                Privacy Policy of every site You visit. We have no control over and assume no responsibility for the
                content, privacy policies or practices of any third party sites or services.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-semibold text-foreground">Changes to this Privacy Policy</h2>

              <p className="text-muted-foreground">
                We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new
                Privacy Policy on this page. We will let You know via email and/or a prominent notice on Our Service,
                prior to the change becoming effective and update the "Last updated" date at the top of this Privacy
                Policy.
              </p>
              <p className="text-muted-foreground mt-2">
                You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy
                Policy are effective when they are posted on this page.
              </p>
            </section>

            <section className="space-y-4 border-t pt-6 mt-8">
              <h2 className="text-2xl font-semibold text-foreground">Contact Us</h2>

              <p className="text-muted-foreground">
                If you have any questions about this Privacy Policy, You can contact us:
              </p>
              <ul className="space-y-2 text-muted-foreground">
                <li>
                  <strong>By email:</strong> info@countryroof.in
                </li>
                <li>
                  <strong>By phone:</strong> +91-9355500043
                </li>
              </ul>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </>
  )
}
