import { Lead, Agent, Activity } from '@/types/lead';

// Remove all mock data - use real database data only
export const mockAgents: Agent[] = [];
export const mockLeads: Lead[] = [];

export const budgetRanges = [
  'Under ₹20,00,000',
  '₹20,00,000 - ₹40,00,000',
  '₹40,00,000 - ₹60,00,000',
  '₹60,00,000 - ₹80,00,000',
  '₹80,00,000 - ₹1,00,00,000',
  '₹1,00,00,000 - ₹2,00,00,000',
  'Over ₹2,00,00,000',
];

export const locations = [
  'Cyber Hub',
  'Sohna Road',
  'DLF Phase 1',
  'DLF Phase 2',
  'DLF Phase 3',
  'DLF Phase 4',
  'DLF Phase 5',
  'Dwarka Expressway',
  'MG Road',
  'Golf Course Road',
  'Golf Course Extn', // Changed 'Golf Course Extension Road' to 'Golf Course Extn' for consistency with your list
  'Sector 29',
  'Sector 14',
  'Sector 56',
  'Sector 62',
  'Sector 45',
  'Ambience Mall',
  'Udyog Vihar',
  'Palam Vihar',
  'Sushant Lok I', // Changed 'Sushant Lok' to 'Sushant Lok I' for clarity as other phases are mentioned
  'Sushant Lok Phase 2',
  'Sushant Lok Phase 3',
  'Sushant Lok Extension',
  'South City', // This covers both South City 1 and South City 2, as commonly referred
  'Manesar',
  'Aravalli Biodiversity Park', // Added as a common landmark in Gurugram
  'Leisure Valley', // Added as a common landmark in Gurugram
  'Sultanpur',
  'Farukh Nagar', // Corrected spelling from 'Farrukhnagar' to 'Farukh Nagar'
  'Sector-54',
  'Sector-43',
  'Sector-25',
  'Sector-50',
  'Sector-49',
  'Sector-95',
  'Sector-47',
  'Sector-48',
  'Sector-27',
  'Sohna Sector-35',
  'Sector-52',
  'Sector-69',
  'Sector-61',
  'Sector-53',
  'Sohna',
  'Sector-33',
  'Sector-42',
  'Sector-66',
  'Sector-31',
  'Sector-24',
  'Sector-22',
  'Sector-51',
  'Sector-81',
  'Sector-15',
  'Sector-67',
  'Sector-82',
  'Sector-83',
  'Sector-57',
  'Sector-37 C',
  'Sector-65',
  'Sector-37 D',
  'Sector-23 A',
  'Sector-86',
  'Sector-46',
  'Sector-110 A',
  'Sector-103',
  'Sector-92',
  'Sector-26',
  'Sector-28',
  'Sector-58',
  'Sector-72',
  'Sector-99A',
  'Sector-70',
  'Sector-59',
  'Sector-79',
  'Sector-38',
  'Sector-1',
  'Sector-30',
  'Sector-80',
  'Sector-41',
  'Sector-7',
  'Sector-109',
  'Sector-3',
  'Sohna Sector-33',
  'Sector-90',
  'Sector-21',
  'Sector-71',
  'Sector-68',
  'Sector-99',
  'Sector-23',
  'Sector-55',
  'Sector-111',
  'Sector-85',
  'Sector-40',
  'Sector-17',
  'Laxman vihar',
  'Sector-9',
  'Sector-108',
  'Sector-70 A',
  'Sector-4',
  'Sohna Sector-2',
  'Sector-107',
  'Sohna Sector-14',
  'Sector-39',
  'Sector-102',
  'Sector-95A',
  'Sector-104',
  'Sector-3(New Palam Vihar)',
  'Sector-84',
  'Sector-10',
  'Sector-89',
  'Patel Nagar',
  'Sector-76',
  'Sector-5',
  'Sector-91',
  'Sector-112',
  'Sector-9 A',
  'Sector-63',
  'Sector-77',
  'Ashok Vihar Phase II',
  'Sector-78',
  'Sector-10 A',
  'NH 8',
  'Palam Vihar Extension',
  'Sector-93',
  'Sector-105',
  'Sector-82 A',
  'Sohna Sector-11',
  'Sohna Sector-36',
  'Sector-32',
  'Old Delhi Gurgaon Road',
  'Ashok Vihar Phase III',
  'Sector-110',
  'Sector-13',
  'Gwal Pahari',
  'Sector-11',
  'New Gurgaon',
  'Sector-3 A',
  'Garhi Harsaru',
  'Manesar Village', // Assuming 'MANESAR VILLAGE' refers to Manesar Village
  'Sector-60',
  'Sector-113',
  'Sector-106',
  'Sector M-1 A',
  'Sector-88B',
  'Sohna Sector-4',
  'Sector-36',
  'Pataudi',
  'Sector-34',
  'Sector-73',
  'Sohna Sector-6',
  'Sector-12',
  'Gurgaon-Faridabad Road',
  'Sector-2',
  'Sector-37',
  'Sector-9 B',
  'Sector-52 A',
  'Sector-102 A',
  'Sector M-3',
  'Udyog Vihar - Industrial Area Phase 4',
  'Sector-6',
  'Sector-89A',
  'Civil Lines',
  'Sector M-11',
  'Bhondsi',
  'Sector-88',
  'Sector-12 A',
  'Sector M-1',
  'Sector M-4',
  'Sector M-7',
  'Sector M-12',
  'Sector-8',
  'Sector-6 A',
  'Sector-88A',
  'Jhajjar Road',
  'Sector-16',
  'Sector-18',
  'Sector-19',
  'Sector-20',
  'Roshan Pura',
  'Sector-35',
  'Sector-44',
  'Sector-114',
  'Sector-103A',
  'Sector-74',
  'Sector-64',
  'Sector-75',
  'Sector-87',
  'Sector-94',
  'Sector-96',
  'Sector-97',
  'Sector-72 A',
  'Sector-98',
  'Sector-100',
  'Sector-101',
  'Sector-115',
  'Sector-26 A',
  'Sector-37 A',
  'Sector-37 B',
  'Sector-74 A',
  'Sector-81 A',
  'Sector M-5',
  'Sector M-6',
  'Sector M-8',
  'Sector M-9',
  'Sector M-10',
  'Sector M-13',
  'Sector M-14',
  'Sector M-15',
  'Sector M-16',
  'Sector M-1 B',
  'Sector M-1 C',
  'Sector M-1 D',
  'Sector M-3 A',
  'Nihal Colony',
  'Sector-95B',
  'Sector-89B',
  'Mankrola',
  'Budhera',
  'Khandsa road',
  'Sohna Sector-7',
  'Bissar Akbarpur',
  'Sohna Sector-5',
  'Sohna Sector-17',
  'Sohna Sector-25',
  'Sohna Sector-34',
];
